### ISSUE TITLE
java.lang.AbstractMethodError on AuthMeVelocity-Paper startup

### ISSUE THREAD

**Issue by noiverre** [4drian3d/AuthMeVelocity#114]
`[08:17:08 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'AuthMeVelocity-Paper-4.0.4.jar' in folder 'plugins'
java.lang.AbstractMethodError: Receiver class io.github._4drian3d.authmevelocity.paper.AuthMeVelocityBootstrap does not define or inherit an implementation of the resolved method 'abstract void bootstrap(io.papermc.paper.plugin.bootstrap.PluginProviderContext)' of interface io.papermc.paper.plugin.bootstrap.PluginBootstrap.
        at io.papermc.paper.plugin.storage.BootstrapProviderStorage$1.load(BootstrapProviderStorage.java:40) ~[paper-1.19.3.jar:git-Paper-420]
        at io.papermc.paper.plugin.storage.BootstrapProviderStorage$1.load(BootstrapProviderStorage.java:28) ~[paper-1.19.3.jar:git-Paper-420]
        at io.papermc.paper.plugin.entrypoint.strategy.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:128) ~[paper-1.19.3.jar:git-Paper-420]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:35) ~[paper-1.19.3.jar:git-Paper-420]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.19.3.jar:git-Paper-420]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enterBootstrappers(LaunchEntryPointHandler.java:26) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.Bootstrap.lambda$bootStrap$0(Bootstrap.java:75) ~[?:?]
        at net.minecraft.core.registries.BuiltInRegistries.bootStrap(BuiltInRegistries.java:319) ~[paper-1.19.3.jar:git-Paper-420]
        at net.minecraft.server.Bootstrap.bootStrap(Bootstrap.java:73) ~[?:?]
        at net.minecraft.server.Main.main(Main.java:115) ~[paper-1.19.3.jar:git-Paper-420]
        at org.bukkit.craftbukkit.Main.main(Main.java:302) ~[paper-1.19.3.jar:git-Paper-420]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

I can provide information but not sure where to start

**Comment by 4drian3d** [comment]
Update to Paper 1.19.4+
