### ISSUE TITLE
cant load on papaer 1.8.8

### ISSUE THREAD

**Issue by Amirmg086** [4drian3d/AuthMeVelocity#158]
error
`08:34:12] [Server thread/ERROR]: Could not load 'plugins\AuthMeVelocity-Paper-4.1.1 (1).jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:152) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:1570) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 6 more`

**Comment by 4drian3d** [comment]
Unsupported
