### ISSUE TITLE
AuthmeVelocity new version dosn't load on 1.8 servers

### ISSUE THREAD

**Issue by Abolfazl-Shaban** [4drian3d/AuthMeVelocity#172]
i cant use new version of AuthmeVelocity-paper 4.0+ on my authme sevrer

Authme server: 
software: paper
verison: 1.8.8

error:

`[20:38:12] [Server thread/ERROR]: Could not load 'plugins\AuthMeVelocity-Paper-4.1.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:152) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 6 more`

**Comment by 4drian3d** [comment]
unsupported version
