### ISSUE TITLE
plugin failed to pass event LoginEvent to AuthMeVelocity in 1.8.8

### ISSUE THREAD

**Issue by skbeh** [4drian3d/AuthMeVelocity#24]
[16:48:24 ERROR]: Could not pass event LoginEvent to AuthMeVelocity v1.4.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[paper.jar:]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[paper.jar:]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paper.jar:]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[paper.jar:]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[paper.jar:]
        at fr.xephi.authme.service.BukkitService.callEvent(BukkitService.java:250) ~[?:?]
        at fr.xephi.authme.process.login.ProcessSyncPlayerLogin.processPlayerLogin(ProcessSyncPlayerLogin.java:102) ~[?:?]
        at fr.xephi.authme.process.SyncProcessManager.lambda$processSyncPlayerLogin$3(SyncProcessManager.java:52) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [paper.jar:]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [paper.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:771) [paper.jar:]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paper.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:701) [paper.jar:]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:604) [paper.jar:]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalAccessError: class com.glyart.authmevelocity.spigot.events.PreSendLoginEvent tried to access method 'void org.bukkit.event.player.PlayerEvent.<init>(org.bukkit.entity.Player, boolean)' (com.glyart.authmevelocity.spigot.events.PreSendLoginEvent is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @1486cb28; org.bukkit.event.player.PlayerEvent is in unnamed module of loader 'app')
        at com.glyart.authmevelocity.spigot.events.PreSendLoginEvent.<init>(PreSendLoginEvent.java:15) ~[?:?]
        at com.glyart.authmevelocity.spigot.listeners.AuthMeListener.onLogin(AuthMeListener.java:26) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[paper.jar:]
        ... 14 more

**Comment by skbeh** [comment]
The [server ](https://github.com/2lstudios-mc/FlamePaper/releases/download/55fa7e6/FlamePaper.jar)version is java 8, and the problem occurs in jdk 11 and jdk 17.

**Comment by 4drian3d** [comment]
This will probably be fixed in the next version, but this is an unsupported version
