### ISSUE TITLE
error on console at startup

### ISSUE THREAD

**Issue by Trinchezito** [4drian3d/AuthMeVelocity#29]
Can anyone help me why, i get this error on the latest build with latest velocity as well? This wasn't happening with the old config. I also updated the config file to match the old one.

`[14:46:30] [Velocity Async Event Executor - #0/INFO]: fastlogin - Starting...
[14:46:30] [Velocity Async Event Executor - #0/INFO]: fastlogin - Start completed.
[14:46:30] [Velocity Async Event Executor - #0/ERROR]: Couldn't pass ProxyInitializeEvent to authmevelocity
java.lang.ClassCastException: class com.glyart.authmevelocity.proxy.config.AuthMeConfig$$Lambda$449/0x0000000801071220 cannot be cast to class com.glyart.authmevelocity.proxy.config.AuthMeConfig$ServerOnLogin (com.glyart.authmevelocity.proxy.config.AuthMeConfig$$Lambda$449/0x0000000801071220 and com.glyart.authmevelocity.proxy.config.AuthMeConfig$ServerOnLogin are in unnamed module of loader com.velocitypowered.proxy.plugin.PluginClassLoader @6e1d4137)
	at com.glyart.authmevelocity.proxy.config.AuthMeConfig.<init>(AuthMeConfig.java:18) ~[?:?]
	at com.glyart.authmevelocity.proxy.AuthMeVelocityPlugin.onProxyInitialization(AuthMeVelocityPlugin.java:49) ~[?:?]
	at com.glyart.authmevelocity.proxy.Lmbda$3.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[server.jar:3.1.2-SNAPSHOT (git-94e8b0df-b121)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[server.jar:3.1.2-SNAPSHOT (git-94e8b0df-b121)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[server.jar:3.1.2-SNAPSHOT (git-94e8b0df-b121)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[14:46:30] [Velocity Async Event Executor - #0/INFO]: Loaded token for website: default`

**Comment by 4drian3d** [comment]
I saw the bug, the problem is because the `ServerOnLogin` section has not been found in your configuration and when trying to assign a default value an error occurred, which appeared by a change that improves performance, but did not get the desired results. In a few minutes I will correct it and release a new version

**Comment by Trinchezito** [comment]
> I saw the bug, the problem is because the `ServerOnLogin` section has not been found in your configuration and when trying to assign a default value an error occurred, which appeared by a change that improves performance, but did not get the desired results. In a few minutes I will correct it and release a new version

Thank you! I got worried lol Had to test things out with cracked and premium accounts to double check that error wasn't affecting anything. thanks again!

**Comment by 4drian3d** [comment]
should be fixed https://github.com/4drian3d/AuthMeVelocity/releases/tag/2.1.1
