### ISSUE TITLE
Couldn't pass ProxyInitializeEvent to authmevelocity

### ISSUE THREAD

**Issue by Envqu** [4drian3d/AuthMeVelocity#32]
Plugin not working
```
[19:43:53] [Velocity Async Event Executor - #0/ERROR]: Couldn't pass ProxyInitializeEvent to authmevelocity
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.minimessage.MiniMessage net.kyori.adventure.text.minimessage.MiniMessage.miniMessage()'
	at com.glyart.authmevelocity.proxy.config.ConfigUtils.<clinit>(ConfigUtils.java:9) ~[?:?]
	at com.glyart.authmevelocity.proxy.config.AuthMeConfig.<init>(AuthMeConfig.java:18) ~[?:?]
	at com.glyart.authmevelocity.proxy.AuthMeVelocityPlugin.onProxyInitialization(AuthMeVelocityPlugin.java:49) ~[?:?]
	at com.glyart.authmevelocity.proxy.Lmbda$3.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[server.jar:3.1.1]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[server.jar:3.1.1]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[server.jar:3.1.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by 4drian3d** [comment]
AuthmeVelocity requires the latest velocity snapshot, download it from papermc.io/downloads
