### ISSUE TITLE
Plugin does not block commands

### ISSUE THREAD

**Issue by Gershon123** [4drian3d/AuthMeVelocity#33]
Hi there, I tried using this plugin on Velocity 3.1.1, I put the proxy file in the velocity plugins folder and the spigot jar into the lobbys plugin folder.

When Velocity is run I see this error:
```[03:01:54] [Velocity Async Event Executor - #0/ERROR]: Couldn't pass ProxyInitializeEvent to authmevelocity
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.minimessage.MiniMessage net.kyori.adventure.text.minimessage.MiniMessage.miniMessage()'
	at com.glyart.authmevelocity.proxy.config.ConfigUtils.<clinit>(ConfigUtils.java:11) ~[?:?]
	at com.glyart.authmevelocity.proxy.config.AuthMeConfig.<init>(AuthMeConfig.java:18) ~[?:?]
	at com.glyart.authmevelocity.proxy.AuthMeVelocityPlugin.onProxyInitialization(AuthMeVelocityPlugin.java:49) ~[?:?]
	at com.glyart.authmevelocity.proxy.Lmbda$7.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[Velocity.jar:3.1.1]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[Velocity.jar:3.1.1]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[Velocity.jar:3.1.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

```
I noticed that the plugin does not block any commands, for example I can still do /server when not logged in. I'm not sure if it's related to that error.

**Comment by 4drian3d** [comment]
https://github.com/4drian3d/AuthMeVelocity#requirements
Update your Velocity version from papermc.io/downloads

**Comment by Gershon123** [comment]
Ahh I totally missed that thank you!
