### ISSUE TITLE
Could not load 'plugins\AuthMeVelocity.jar' in folder 'plugins'  - Paper

### ISSUE THREAD

**Issue by nazmiyigitefe** [4drian3d/AuthMeVelocity#52]
```
[01:40:44] [Server thread/ERROR]: Could not load 'plugins\AuthMeVelocity.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `me.adrianed.authmevelocity.paper.AuthMeVelocityPaper'
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:75) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:419) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:291) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.adrianed.authmevelocity.paper.AuthMeVelocityPaper
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:73) ~[patched_1.17.1.jar:git-Pufferfish-22]
	... 8 more
```

**Comment by 4drian3d** [comment]
Can you try this build https://github.com/4drian3d/AuthMeVelocity/actions/runs/2870802230 ?

**Comment by nazmiyigitefe** [comment]
I tried that build but:

```
[03:30:47] [Server thread/INFO]: [AuthMeVelocity] Enabling AuthMeVelocity v3.0.0
[03:30:47] [Server thread/ERROR]: Error occurred while enabling AuthMeVelocity v3.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/typesafe/config/ConfigException
	at me.adrianed.authmevelocity.common.configuration.Loader.loadMainConfig(Loader.java:18) ~[AuthMeVelocity.jar:?]
	at me.adrianed.authmevelocity.paper.AuthMeVelocityPlugin.onEnable(AuthMeVelocityPlugin.java:31) ~[AuthMeVelocity.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:735) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:321) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.typesafe.config.ConfigException
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 12 more
[03:30:47] [Server thread/INFO]: [AuthMeVelocity] Disabling AuthMeVelocity v3.0.0
```

**Comment by 4drian3d** [comment]
Try the latest release "3.0.1"

**Comment by nazmiyigitefe** [comment]
Same error, ConfigException.

`[03:30:47] [Server thread/INFO]: [AuthMeVelocity] Enabling AuthMeVelocity v3.0.1
[03:30:47] [Server thread/ERROR]: Error occurred while enabling AuthMeVelocity v3.0.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/typesafe/config/ConfigException
	at me.adrianed.authmevelocity.common.configuration.Loader.loadMainConfig(Loader.java:18) ~[AuthMeVelocity.jar:?]
	at me.adrianed.authmevelocity.paper.AuthMeVelocityPlugin.onEnable(AuthMeVelocityPlugin.java:31) ~[AuthMeVelocity.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:735) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:321) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.typesafe.config.ConfigException
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[patched_1.17.1.jar:git-Pufferfish-22]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 12 more
[03:30:47] [Server thread/INFO]: [AuthMeVelocity] Disabling AuthMeVelocity v3.0.1`

**Comment by 4drian3d** [comment]
Delete the "libs" folder in the AuthMeVelocity folder, so it will download the dependencies again
